version: "3"

tasks:
  default:
    cmd: task --list

  clean:
    desc: Cleans .astro cache
    cmds: 
      - rm -rf .astro/
      - pnpm astro sync

  deps:
    desc: Pulls dependencies
    cmd: pnpm install

  serve:
    desc: Runs all servers
    deps:
      - serve:astro

  serve:astro:
    desc: Runs Astro
    cmd: pnpm astro dev

  preview:
    desc: Previews the site
    cmd: pnpm astro preview

  astro:
    desc: Runs `astro` CLI
    cmd: pnpm astro

  check:
    desc: Runs checks & linters
    cmds:
      - npx eslint content/**
      - pnpm astro check

  build:
    desc: Builds production app
    env:
      NODE_ENV: production
    cmds:
      - pnpm astro check
      # - npx tailwindcss -i src/styles/global.css -o static/styles/styles.css
      - pnpm astro build
